---
# Функциональные требования
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять и удалять товары в корзине и просматривать содержимое корзины

# Нефункциональные требования
non-functional:
- Сайт должен иметь мобильную версию
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт представляет из себя SPA (Single page application) приложение, которое не перезагружает страницу
- На странице товара и в каталоге выводится - название, рейтинг, цена со скидкой и без

# Неявные требования
implicit:
- Пользователь должен иметь возможность добавлять товары в избранное
- Пользователь должен иметь возможность просматривать совершенные заказы
- Пользователь должен иметь возможность выбрать вид получения товара - самовывоз / доставка
- Возможность выбрать пустое значение в фильтре-категорий товаров, которое отображает все товары вне зависимости от категории
