---
# Функциональные требования
functional:
- Возможность искать товары по ключевому слову
- Возможность искать товары по категории
- Возможность фильтровать товары по цене
- Возможность фильтровать товары по размеру
- Возможность просматривать товары
- Возможность просматривать подробную информацию о товаре
- Возможность добавлять товары в корзину
- Возможность просматривать содержимое корзины

# Нефункциональные требования
non-functional:
- Сайт должен иметь мобильную версию
- Сайт должен быть безопасным и защищать данные пользователя
- Протестировать сайт на совместимость с последними версиями браузеров

# Неявные требования
implicit:
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах.
